<!-- Footer design inspired from https://www.youtube.com/watch?v=nkZz9DOBzBI -->
<div id="footer-container">
    <p>Our Socials</p>
    
    <div id="footer-navigation">
        <ul>
            <li><a href="https://wtp-project.atlassian.net/jira/software/projects/SCRUM/boards/1">Jira</a></li>
            <li><a href="https://github.com/104874063/Web_Tech_Project_Part_2">GitHub</a></li>
            <li><a href="mailto:info@companyname.com">Email</a></li>
        </ul>
    </div>
</div>
<hr>
<p>&copy; 2025 Swinburne Government Association. All rights reserved.</p>